In [1]:
import numpy as np

In [10]:
a = [[1,2,3] , [4,5,6]]


In [11]:
num_array = np.array(object= num_array)

Que1: write a code to find the characteristics of variable , num_array

In [12]:
np.shape(a)

(2, 3)

In [13]:
np.size(a)

6

Que 2: write a code to create numpy array of 3*3 matrix containing zeros only, using numpy array creation function

In [15]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Que3: create an identity matrix of shape(5,5) using numpy function?

In [54]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Que4: is there any difference of data type of variable list and array list ? if there is then write a code tp print the data type of both the variables.

In [11]:
import numpy as np

In [12]:
s= ['1' , '2' , '3' , '4', '5']

In [15]:
array_list= np.array(object=list)

In [16]:
np.array(s)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [17]:
d=[1,2,3,4,5]

In [18]:
np.array(d)

array([1, 2, 3, 4, 5])

In [25]:
np.dtype

numpy.dtype